name: Lint
run-name: ${{ github.actor }} is running our tests 🚀
on: [pull_request]
jobs:
  Pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint --rcfile=pylintrc --fail-under=7.93 serial/ test/ # 7.94 is what the main branch was scoring when this project was created.
