name: Lint
run-name: ${{ github.actor }} is running our tests 🚀
on: [pull_request]
jobs:
  Pylint:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4

      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint --rcfile=pylintrc --disable=R,C,W serial/ 
